{% set name = "perl-math-matrix" %}
{% set version = "0.9" %}
{% set sha256 = "b28e25f602e07ac4b8ca70c18f7a9c308eeaec989efe2415e1d529f9d461795a" %}

package:
  name: perl-math-matrix
  version: "0.9"

source:
  url: https://cpan.metacpan.org/authors/id/P/PJ/PJACKLAM/Math-Matrix-0.9.tar.gz
  sha256: b28e25f602e07ac4b8ca70c18f7a9c308eeaec989efe2415e1d529f9d461795a

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  # Perl 'use' tests
  imports:
    - Math::Matrix

about:
  home: https://metacpan.org/pod/Math::Matrix
  license: unknown
  summary: 'Multiply and invert Matrices'
