{% set name = "artic-tools" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/will-rowe/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: f4f7ec5400bf1ac0abcda45e313730d6d29805c515f573fe2c1c0d69dc8be129

https://github.com/will-rowe/artic-tools/archive/v0.1.0.tar.gz

build:
  number: 0
  skip: True #  [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - htslib=1.9
  run:
    - htslib=1.9

test:
  commands:
    - artic-tools -h

about:
  home: https://github.com/will-rowe/artic-tools
  license: MIT
  license_file: LICENSE
  summary: A set of tools for working with the ARTIC bioinformatic pipeline.
